services:
  ryanpdf:
    build:
      context: ../..
      dockerfile: docker/embedded/Dockerfile.fat
    container_name: ryanpdf-fat
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 6G
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080$${SYSTEM_ROOTURIPATH:-''}/api/v1/info/status | grep -q 'UP'"]
      interval: 5s
      timeout: 10s
      retries: 16
    ports:
      - "8080:8080"
    volumes:
      - ../../ryanpdf/latest/data:/usr/share/tessdata:rw
      - ../../ryanpdf/latest/config:/configs:rw
      - ../../ryanpdf/latest/logs:/logs:rw
    environment:
      DISABLE_ADDITIONAL_FEATURES: "false"
      SECURITY_ENABLELOGIN: "true"
      SECURITY_INITIALLOGIN_USERNAME: "truonghv1988"
      SECURITY_INITIALLOGIN_PASSWORD: "Ittruonghv1988@"
      FAT_DOCKER: "true"
      SYSTEM_DEFAULTLOCALE: en-US
      UI_APPNAME: RyanPDF
      UI_HOMEDESCRIPTION: Full-featured RyanPDF with all capabilities
      UI_APPNAMENAVBAR: RyanPDF Fat
      SYSTEM_MAXFILESIZE: "200"
      METRICS_ENABLED: "true"
      SYSTEM_GOOGLEVISIBILITY: "true"
      SHOW_SURVEY: "true"
    networks:
      - ryanpdf-network

networks:
  ryanpdf-network:
    driver: bridge

volumes:
  ryanpdf-data:
  ryanpdf-config:
  ryanpdf-logs:
