services:
  ryanpdf:
    build:
      context: ../..
      dockerfile: docker/embedded/Dockerfile
    container_name: ryanpdf
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080$${SYSTEM_ROOTURIPATH:-''}/api/v1/info/status | grep -q 'UP'"]
      interval: 5s
      timeout: 10s
      retries: 16
    ports:
      - "8080:8080"
    volumes:
      - ../../ryanpdf/latest/data:/usr/share/tessdata:rw
      - ../../ryanpdf/latest/config:/configs:rw
      - ../../ryanpdf/latest/logs:/logs:rw
    environment:
      DISABLE_ADDITIONAL_FEATURES: "true"
      SECURITY_ENABLELOGIN: "true"
      SECURITY_INITIALLOGIN_USERNAME: "${SECURITY_INITIALLOGIN_USERNAME}"
      SECURITY_INITIALLOGIN_PASSWORD: "${SECURITY_INITIALLOGIN_PASSWORD}"
      SYSTEM_DEFAULTLOCALE: en-US
      UI_APPNAME: RyanPDF
      UI_HOMEDESCRIPTION: Demo site for RyanPDF Latest
      UI_APPNAMENAVBAR: RyanPDF Latest
      SYSTEM_MAXFILESIZE: "100"
      METRICS_ENABLED: "true"
      SYSTEM_GOOGLEVISIBILITY: "true"
      SHOW_SURVEY: "true"
    networks:
      - ryanpdf-network

networks:
  ryanpdf-network:
    driver: bridge

volumes:
  ryanpdf-data:
  ryanpdf-config:
  ryanpdf-logs:
